"""Vehicles created_at and updated_at nullable false

Revision ID: 29971d4f5ea3
Revises: 943b5a037c79
Create Date: 2025-05-14 15:38:34.620528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29971d4f5ea3'
down_revision: Union[str, None] = '943b5a037c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vehicles', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
