"""updated e created at no vehicles

Revision ID: 385ff381fa76
Revises: 5682200c3c43
Create Date: 2025-05-12 14:02:38.417202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385ff381fa76'
down_revision: Union[str, None] = '5682200c3c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'last_updated')
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###
