services:
  postgres:
    image: postgres:latest
    container_name: dieselman_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: its3437not4you
      POSTGRES_DB: top
    volumes:
      - dieselman:/var/lib/postgresql/data

volumes:
  dieselman:
