services:
  postgres:
    image: postgres:latest
    container_name: production
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: its3437not4you
      POSTGRES_DB: top
    volumes:
      - pg_data_production:/var/lib/postgresql/data

volumes:
  pg_data_production:
